include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "examples/**"
    - "**.g.dart"
    - "**.freezed.dart"
    - "packages/flusmic/test/.test_coverage.dart"
  errors:
    include_file_not_found: ignore
