include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "examples/**"
    - "packages/flusmic/lib/example/**"
    - "packages/flusmic/test/.test_coverage.dart"
    - "packages/flusmic_ui/lib/example/**"
  errors:
    include_file_not_found: ignore
