include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - examples/**
    - "**.g.dart"
    - "**.freezed.dart"
    # - lib/src/models/api/**.g.dart
    # - lib/src/models/document/**.g.dart
    # - lib/src/models/ordering/**.freezed.dart
    # - lib/src/models/predicate/**.freezed.dart
    # - lib/src/models/result/**.g.dart
    # - lib/src/models/serializer/**.g.dart
    # - lib/src/models/types/**.g.dart
    # - lib/src/widgets/**.freezed.dart
  errors:
    include_file_not_found: ignore
