name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 4.0.1
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dio: ^5.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  coverage: ^1.6.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  nock: ^1.2.2
  test: ^1.24.2
  very_good_analysis: ^4.0.0+1

screenshots:
  - description: 'Flusmic banner'
    path: images/flusmic.png