name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 3.0.1
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  dio: ^4.0.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  nock: ^1.2.0
  test: ^1.17.5
  very_good_analysis: ^2.1.1
