name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 2.0.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.1.0
  freezed_annotation: ^0.7.1
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  effective_dart: ^1.2.1
  freezed: ^0.10.7
  json_serializable: ^3.3.0
  mockito: ^4.1.1
  nock: ^1.0.1
  test: ^1.14.3