name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 3.2.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^3.2.0
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.1.0
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  nock: ^1.2.0
  test: ^1.20.1
  very_good_analysis: ^2.4.0