name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 3.0.1
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.3.0
  dio: ^4.0.0
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  coverage: ^1.0.3
  freezed: ^0.14.5
  json_serializable: ^5.0.2
  nock: ^1.2.0
  test: ^1.18.0
  very_good_analysis: ^2.3.0
