name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 3.2.3
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.1.11
  coverage: ^1.3.2
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  nock: 1.1.3
  test: ^1.21.1
  very_good_analysis: ^3.0.0