name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 3.0.0-nullsafety.1
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-beta6
  freezed_annotation: ^0.14.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  freezed: ^0.14.0+1
  json_serializable: ^4.0.2
  nock: ^1.2.0
  test: ^1.16.5
  very_good_analysis: ^2.0.0
