name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 4.0.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  nock: ^1.2.1
  test: ^1.23.1
  very_good_analysis: ^4.0.0+1

screenshots:
  - description: 'Flusmic banner'
    path: images/flusmic.png