name: flusmic
description: A functional and kind of elegant Prismic.io integration for Dart and Flutter.
version: 2.1.0
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.0-beta1
  freezed_annotation: ^0.13.0-nullsafety.0
  json_annotation: ^4.0.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^1.11.5
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.1
  nock: ^1.1.2
  test: ^1.16.4
  very_good_analysis: ^2.0.0-nullsafety.0
