name: flusmic_ui
description: A collection of widgets, utilities and extensions to integrate Flusmic more easy in Flutter.
version: 1.0.0+1
repository: https://github.com/PixelaGt/flusmic
issue_tracker: https://github.com/PixelaGt/flusmic/issues
homepage: https://github.com/PixelaGt/flusmic

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  common_bloc: ^2.0.3
  flusmic: ^2.0.0+2
  freezed_annotation: ^0.11.0
  state_notifier: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  effective_dart: ^1.2.2
  freezed: ^0.11.0
  mockito: ^4.1.1

flutter:
  #
