name: flusmic

on:
  push:
    paths:
      - "packages/flusmic/**"
      - ".github/workflows/flusmic.yaml"
  pull_request:
    paths:
      - "packages/flusmic/**"
      - ".github/workflows/flusmic.yaml"

jobs:
  flusmic-build:
    defaults:
      run:
        working-directory: packages/flusmic
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.8.1
    steps:
      - uses: actions/checkout@v2
      - name: get dependencies
        run: pub get
      - name: valid format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: analyze
        run: dartanalyzer .
      - name: run tests
        run: pub run test_coverage
      - name: check coverage percentage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: "./packages/flusmic/coverage/lcov.info"
          min_coverage: 85
          exclude: "**/*.g.dart **/*.freezed.dart lib/src/models/**"
      - name: upload coverage
        uses: codecov/codecov-action@v1